/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 AtriumFireGraphic.glb -K
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/fire-suppression-graphic/AtriumFireGraphic.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <group position={[-1.5, 1.5, 0]} scale={[0.25, 2, 0.25]} />
        <group position={[-1.5, -0.5, 0]} scale={[0.25, 2, 0.25]} />
        <group position={[-2, 0, 0]} scale={[0.25, 2, 0.25]} />
        <group position={[0.97, -1.68, 0]} scale={0.5} />
        <group position={[0.46, -1.62, 0]} scale={0.5} />
        <group position={[-0.4, -1.62, 0]} scale={0.5} />
        <group position={[-0.8, 1.5, 1.05]} scale={[0.25, 2, 0.25]} />
        <group position={[0, 0, 0.41]} scale={[0.25, 2, 0.25]} />
        <group position={[0, 2.48, 0.47]} scale={[0.25, 2, 0.25]} />
        <group position={[1.8, 1.45, 0.47]} scale={[0.25, 2, 0.25]} />
        <group>
          <mesh geometry={nodes.Mesh.geometry} material={materials.ClearWalls} />
          <mesh geometry={nodes.Mesh_1.geometry} material={materials.BlackOutlines} />
        </group>
        <mesh geometry={nodes.FireSubstrate.geometry} material={nodes.FireSubstrate.material} position={[0, -1.99, 0]} />
        <mesh geometry={nodes.FireEmitter.geometry} material={nodes.FireEmitter.material} position={[0, -1.87, 0]} scale={0.25} />
        <mesh geometry={nodes.SmokeLayerEmitter.geometry} material={nodes.SmokeLayerEmitter.material} position={[0, 1.99, 0]} />
        <mesh geometry={nodes.PlumeEmitter.geometry} material={nodes.PlumeEmitter.material} position={[0, -1.87, 0]} />
        <group>
          <mesh geometry={nodes.Cube005.geometry} material={materials.ClearWalls} />
          <mesh geometry={nodes.Cube005_1.geometry} material={materials.BlackOutlines} />
        </group>
        <group position={[0, -0.63, 0]}>
          <mesh geometry={nodes.Cube005_2.geometry} material={materials.ClearWalls} />
          <mesh geometry={nodes.Cube005_3.geometry} material={materials.BlackOutlines} />
        </group>
        <group position={[0, -1.25, 0]}>
          <mesh geometry={nodes.Cube005_4.geometry} material={materials.ClearWalls} />
          <mesh geometry={nodes.Cube005_5.geometry} material={materials.BlackOutlines} />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={-1}>
          <mesh geometry={nodes.Cube006.geometry} material={materials.ClearWalls} />
          <mesh geometry={nodes.Cube006_1.geometry} material={materials.BlackOutlines} />
        </group>
        <group position={[0, -0.63, 0]} rotation={[-Math.PI, 0, 0]} scale={-1}>
          <mesh geometry={nodes.Cube006_2.geometry} material={materials.ClearWalls} />
          <mesh geometry={nodes.Cube006_3.geometry} material={materials.BlackOutlines} />
        </group>
        <group position={[0, -1.25, 0]} rotation={[-Math.PI, 0, 0]} scale={-1}>
          <mesh geometry={nodes.Cube006_4.geometry} material={materials.ClearWalls} />
          <mesh geometry={nodes.Cube006_5.geometry} material={materials.BlackOutlines} />
        </group>
        <group position={[0, 2.14, 0]}>
          <mesh geometry={nodes.Cube007.geometry} material={materials.ClearWalls} />
          <mesh geometry={nodes.Cube007_1.geometry} material={materials.BlackOutlines} />
        </group>
        <mesh geometry={nodes.TopSmokeEmitter.geometry} material={nodes.TopSmokeEmitter.material} position={[0, 2.38, 0]} scale={0.38} />
        <group position={[0, 2.07, 0]} scale={0.05}>
          <mesh geometry={nodes.Cylinder002.geometry} material={materials.ClearWalls} />
          <mesh geometry={nodes.Cylinder002_1.geometry} material={materials.BlackOutlines} />
        </group>
        <group position={[1.39, 1.35, 0]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Cube008.geometry} material={materials.ClearWalls} />
          <mesh geometry={nodes.Cube008_1.geometry} material={materials.BlackOutlines} />
        </group>
        <mesh geometry={nodes.SideSmokeEmitter.geometry} material={nodes.SideSmokeEmitter.material} position={[1.64, 1.35, 0]} rotation={[0, 0, -Math.PI / 2]} scale={0.38} />
        <group position={[1.34, 1.35, 0]} rotation={[0, 0, -Math.PI / 2]} scale={0.05}>
          <mesh geometry={nodes.Cylinder004.geometry} material={materials.ClearWalls} />
          <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.BlackOutlines} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fire-suppression-graphic/AtriumFireGraphic.glb')
